

GAME_STATUS_READY = 'Ready'
GAME_STATUS_IN_PROGRESS = 'In Progress'
GAME_STATUS_LOST = 'Lost'
GAME_STATUS_WON = 'Won'
GAME_STATUS_INIT = 'INIT'
GAME_STATUS_ABANDONED = 'Abandoned'



CELL_STATUS_HIDDEN = 0 # available
CELL_STATUS_EXPOSED = 1
CELL_STATUS_FLAG = 2
CELL_STATUS_FLAG_MAYBE = 3
CELL_STATUS_BOOM = 4
CELL_STATUS_BOMB_EXPOSED = 5 
CELL_STATUS_FLAG_WAS_WRONG = 6
